CREATE DATABASE megastore;

CREATE TABLE costumers (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(120) NOT NULL,
	email VARCHAR(240) NOT NULL,
	address VARCHAR(120) NOT NULL,
	phone VARCHAR(120) NOT NULL
)
